name: ❓ 질문 및 도움 요청
description: 패키지 사용법에 대한 질문이나 도움을 요청해주세요
title: "[QUESTION] "
labels: ["question", "help wanted"]

body:
  - type: markdown
    attributes:
      value: |
        ## ❓ 질문 및 도움 요청
        
        패키지 사용에 대한 질문을 해주셔서 감사합니다! 더 정확한 답변을 드릴 수 있도록 아래 정보를 작성해주세요.
        
        > 💡 **팁**: 먼저 [문서](링크)와 [예제](링크)를 확인해보시고, 기존 이슈에서 비슷한 질문이 있었는지 검색해보세요!

  - type: textarea
    id: question
    attributes:
      label: 📝 질문 내용
      description: 구체적인 질문을 명확하게 작성해주세요
      placeholder: |
        예) 
        - 카카오맵에서 특정 위치로 이동하는 방법이 있나요?
        - 카카오맵 지도 테마를 변경하는 방법이 있나요?
    validations:
      required: true

  - type: input
    id: package-version-q
    attributes:
      label: 📦 패키지 버전
      description: 사용 중인 패키지 버전을 입력해주세요
      placeholder: 예) 1.0.0
    validations:
      required: true

  - type: input
    id: flutter-version-q
    attributes:
      label: 🔧 Flutter 버전
      description: flutter --version 명령어 결과를 입력해주세요
      placeholder: 예) Flutter 3.16.0
    validations:
      required: true

  - type: checkboxes
    id: platforms-q
    attributes:
      label: 📱 플랫폼
      description: 어떤 플랫폼에서 작업하고 있나요?
      options:
        - label: Android
        - label: iOS